name: Test NeoGrammarGraph

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-key adv --keyserver keys.openpgp.org --recv-key 612DEFB798507F25
        sudo add-apt-repository -y "deb [ arch=amd64 ] https://downloads.skewed.de/apt jammy main"
        sudo apt-get update
        sudo apt-get install -y python3-graph-tool
        pip install --upgrade pip
        pip install -e .[dev,test]
       
        which python3 
        find /usr/lib -d -name "graph_tool"
    - name: Test with pytest
      run: |
        python3 -m pytest --html=report.html --self-contained-html --cov-report xml:coverage.xml --cov-report term --cov-config=.coveragerc --cov=gg tests/
        python3 -m coverage lcov
    - uses: actions/upload-artifact@v3
      with:
        name: Test Report
        path: report.html
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
